### ISSUE TITLE
Error loading data

### ISSUE THREAD

**Issue by Tomasxxx** [sergejbubko/HODLcube#5]
Problém: error  loading data. Check wifi connection or increase screen change delay in config. Was Done reset,also upload latest firmware v05.1 ,but problém still persist. Is possible to access to config page ,ping also working. Thank fór advise.
![IMG_20240224_094207](https://github.com/sergejbubko/HODLcube/assets/84733699/564e0a68-ecd5-41b1-9573-382fc730068d)

**Comment by sergejbubko** [comment]
Hi, sorry for the inconvenience. I will make update asap. I noticed this yesterday evening. Unfortunately, Coinbase changed their API and the returned json is longer than HODLcube can parse at the moment due to insufficient memory allocated. I will send an e-mail to all users, because I don't think that everyone can use GitHub like you do.

Regards, Václav

**Comment by Tomasxxx** [comment]
Hi  thank fór quick replay .Yes exactly IT started Yesterday evening  . Thank fór support.
